/*
  app.js -- This creates an Express webserver
*/

import {PlayerWord} from './PlayerWord'
import {Player} from './Player'


// First we load in all of the packages we need for the server...
const createError = require("http-errors");
const express = require("express");
const path = require("path");
const cookieParser = require("cookie-parser");
const session = require("express-session");
//const bodyParser = require("body-parser");
const axios = require("axios");
var debug = require("debug")("personalapp:server");

// Now we create the server
const app = express();

// Here we specify that we will be using EJS as our view engine
app.set("views", path.join(__dirname, "views"));
app.set("view engine", "ejs");

// Here we process the requests so they are easy to handle
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());

// Here we specify that static files will be in the public folder
app.use(express.static(path.join(__dirname, "public")));

// Here we enable session handling ..
app.use(
  session({
    secret: "zzbbya789fds89snana789sdfa",
    resave: false,
    saveUninitialized: false
  })
);

//app.use(bodyParser.urlencoded({ extended: false }));

// This is an example of middleware
// where we look at a request and process it!
app.use(function(req, res, next) {
  //console.log("about to look for routes!!! "+new Date())
  console.log(`${req.method} ${req.url}`);
  //console.dir(req.headers)
  next();
});

console.log("I am running!")

// here we start handling routes
app.get("/", (req, res) => {
  res.render("index");
});


var players: Player[] = [new Player(0),new Player(1)]

app.get('/word', (req,res) => {
  res.locals.extrastuff = ''
  for (var player of players){
    res.locals.extrastuff += player.display()
  }
  res.render('wordSubmit')
})

app.post('/submitWord',(req,res) => {
  players[req.body.number].makeWord(req.body.word)
  res.locals.extrastuff = players.map(x => x.display())
  res.render('wordSubmit')
})

app.post('/guessWord',(req,res) => {
  const guess = req.body.guess

  players[0].takeDamage(players[req.body.number].guessLetter(guess))
  res.locals.extrastuff = players.map(x => x.display())
  res.render('wordSubmit')
})


app.get("/json", (req, res) => {
  res.render("json");
});

app.post("/jsonResult",
  async (req,res,next) => {
    try {
      const url = req.body.url
      const key = req.body.key

      const result = await axios.get("https://abusiveexperiencereport.googleapis.com/v1/sites/" + url + "?key=" + key)

      res.locals.abusiveStatus = result.data.abusiveStatus
      res.locals.url = req.body.url
      res.locals.key = req.body.key

      console.log(result.data)
      res.render('jsonResult')
    } catch(error){
      next(error)
    }


}

)


// Don't change anything below here ...

// here we catch 404 errors and forward to error handler
app.use(function(req, res, next) {
  next(createError(404));
});

// this processes any errors generated by the previous routes
app.use(function(err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get("env") === "development" ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render("error");
});

//Here we set the port to use
const port = "5000";
app.set("port", port);

// and now we startup the server listening on that port
const http = require("http");
const server = http.createServer(app);

server.listen(port);

function onListening() {
  var addr = server.address();
  var bind = typeof addr === "string" ? "pipe " + addr : "port " + addr.port;
  debug("Listening on " + bind);
}

function onError(error) {
  if (error.syscall !== "listen") {
    throw error;
  }

  var bind = typeof port === "string" ? "Pipe " + port : "Port " + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case "EACCES":
      console.error(bind + " requires elevated privileges");
      process.exit(1);
      break;
    case "EADDRINUSE":
      console.error(bind + " is already in use");
      process.exit(1);
      break;
    default:
      throw error;
  }
}

server.on("error", onError);

server.on("listening", onListening);

module.exports = app;
